name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - run: npm ci
    - run: npm test -- --watchAll=false
    - run: npm run build
    
    - name: Verify build
      run: |
        test -f dist/manifest.json && test -f dist/popup.html && 
        test -f dist/popup.js && test -f dist/background.js
        
    - uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: dist/

  release:
    if: github.event_name == 'release'
    needs: test-and-build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    
    - name: Package extension
      run: |
        cd dist && zip -r ../extension.zip .
        
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./extension.zip
        asset_name: documentation-tab-grouper.zip
        asset_content_type: application/zip
