name: Release

on:
  release:
    types: 
        - published

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build
    
    - name: Package extension
      run: |
        cd dist && zip -r ../extension.zip .
        
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./extension.zip
        asset_name: tabby.zip
        asset_content_type: application/zip
